export const lightColors = {
    backgroundBar: '#ffffff',
    backgroundContainer: '#E6E6E6',
    backgroundPressed: '#1f2937',
    backgroundHover: '#1f2937',
    texto: '#000000',
    subTexto: '#838383ff',
    textoHover: '#fff',
    textoPressed: '#fff',
    linea: '#bbb',
    primary: '#007bffff',
    icono: '#000000',
    iconoHover: '#fff',
    iconoPressed: '#fff',
    input:'#ccc',
    backgroundRowTable1: '#f0f0f0ff',
    backgroundRowTable2: '#fCfCfCff',
    backgroundRowTableHover: '#a8a8a8ff',
    backgroundRowTablePressed: '#939393ff',
};

export const darkColors = {
    backgroundBar: '#1f2937',
    backgroundContainer: '#394352ff',
    backgroundPressed: '#fff',
    backgroundHover: '#fff',
    texto: '#ffffff',
    subTexto: '#cbd5e1',
    textoHover: '#1f2937',
    textoPressed: '#1f2937',
    linea: '#ccc',
    primary: '#3c9effff',
    icono: '#ffffff',
    iconoHover: '#1f2937',
    iconoPressed: '#1f2937',
    input:'#666',
    backgroundRowTable1: '#394352ff',
    backgroundRowTable2: '#4e5c71ff',
    backgroundRowTableHover: '#29303bff',
    backgroundRowTablePressed: '#1c2028ff',
};